### ISSUE TITLE
Syntax error on password while setting up plex

### ISSUE THREAD

**Issue by cyb3rgh05t** [Sleepingpirates/Invitarr#40]
i get this error when i try to register a password:

```
Ignoring exception in command setupplex:
today at 21:33:43Traceback (most recent call last):
today at 21:33:43  File "/app/app/bot/helper/confighelper.py", line 84, in change_config
today at 21:33:43    config.set(BOT_SECTION, key, str(value))
today at 21:33:43  File "/usr/local/lib/python3.9/configparser.py", line 1201, in set
today at 21:33:43    super().set(section, option, value)
today at 21:33:43  File "/usr/local/lib/python3.9/configparser.py", line 894, in set
today at 21:33:43    value = self._interpolation.before_set(self, section, option,
today at 21:33:43  File "/usr/local/lib/python3.9/configparser.py", line 402, in before_set
today at 21:33:43    raise ValueError("invalid interpolation syntax in %r at "
today at 21:33:43ValueError: invalid interpolation syntax in '4;!W%6*~u^X&|KZyDwl' at position 4
today at 21:33:43
today at 21:33:43During handling of the above exception, another exception occurred:
today at 21:33:43
today at 21:33:43Traceback (most recent call last):
today at 21:33:43  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
today at 21:33:43    ret = await coro(*args, **kwargs)
today at 21:33:43  File "/app/run.py", line 88, in setupplex
today at 21:33:43    confighelper.change_config("plex_pass", str(password))
today at 21:33:43  File "/app/app/bot/helper/confighelper.py", line 86, in change_config
today at 21:33:43    config.add_section(BOT_SECTION)
today at 21:33:43  File "/usr/local/lib/python3.9/configparser.py", line 1208, in add_section
today at 21:33:43    super().add_section(section)
today at 21:33:43  File "/usr/local/lib/python3.9/configparser.py", line 659, in add_section
today at 21:33:43    raise DuplicateSectionError(section)
today at 21:33:43configparser.DuplicateSectionError: Section 'bot_envs' already exists
today at 21:33:43
today at 21:33:43The above exception was the direct cause of the following exception:
today at 21:33:43
today at 21:33:43Traceback (most recent call last):
today at 21:33:43  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
today at 21:33:43    await ctx.command.invoke(ctx)
today at 21:33:43  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
today at 21:33:43    await injected(*ctx.args, **ctx.kwargs)
today at 21:33:43  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
today at 21:33:43    raise CommandInvokeError(exc) from exc
today at 21:33:43discord.ext.commands.errors.CommandInvokeError: Command raised an exception: DuplicateSectionError: Section 'bot_envs' already exists
```
is there a possible fix?

thanks

**Comment by cyb3rgh05t** [comment]
changed now my password for plex but now i get this error:
```
Error with plex login. Please check username and password and Plex server name or setup plex in the bot.
```
but all credentials are correct

**Comment by srvoets** [comment]
> changed now my password for plex but now i get this error:
> 
> ```
> Error with plex login. Please check username and password and Plex server name or setup plex in the bot.
> ```
> 
> but all credentials are correct

Same, came here looking for a solution
